# Codeceptjs based BDD testing

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    CSP_HOST=_local npm run ci -- --grep @noauth
  displayName: 'first test'

